name: medfree
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.5.3
  percent_indicator: ^4.2.5
  fl_chart: ^0.68.0
  intl: ^0.19.0
  http: ^1.2.1
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env
    # Ensure these asset paths match the actual filenames in your assets/ directory
    - assets/thrive_being.png
    - assets/medfree.png
    - assets/splash_logo.png
    - assets/medfree1.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/thrive_being.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
